### ISSUE TITLE
Unable to obtain 12cgpFdJViXbwHbhrA3TuW1EGnL25Zqc3P wallet balance 

### ISSUE THREAD

**Issue by timmermankelly4** [btccom/Blockchain-Known-Pools#19]
Please help me with wallet issues.

**Comment by PeiyuYang** [comment]
https://btc.com/12cgpFdJViXbwHbhrA3TuW1EGnL25Zqc3P 
https://chain.api.btc.com/v3/address/12cgpFdJViXbwHbhrA3TuW1EGnL25Zqc3P

**Comment by yoon1220** [comment]
Please help me i cannot access my btc address some is change my btc address

**Comment by yoon1220** [comment]
1H6ZZpRmMnrw8ytepV3BYwMjYYnEkWDqVP
