### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by StemRoot** [btccom/Blockchain-Known-Pools#21]

**Comment by StemRoot** [comment]
I need further advice

**Comment by PeiyuYang** [comment]
What  mean?
I don't know what your question？

**Comment by StemRoot** [comment]
I've been trying to update my address so that when I do a block transaction they verify my wallet address and instead of block chain using my wallet address they put unknown address or address cant be encoded now I feel like I've lost my main address in the 2month process of when I started building blocks
