### ISSUE TITLE
New pool  need to add

### ISSUE THREAD

**Issue by zhoujianwei** [btccom/Blockchain-Known-Pools#25]
"/DPOOL.TOP/": {
+            "name" : "DPOOL",
+            "link" : "http://www.dpool.top/"
+        },

or

"1ACAgPuFFidYzPMXbiKptSrwT74Dg8hq2v": {
+            "name" : "DPOOL",
+            "link" : "http://www.dpool.top/"
+        },

our pool  will open soon

**Comment by PeiyuYang** [comment]
你好， 提交中的链接目前访问是404 http://www.dpool.top 。

**Comment by zhoujianwei** [comment]
现在限制ip访问，我们目前有1021p算力，
![logo2 724f929](https://user-images.githubusercontent.com/4134294/38181935-762e38ea-3668-11e8-8ac5-c96d0dbc1b3c.png)
稍后对外开发。希望贵站btc.com同步更新下区块标识为DPOOL

**Comment by PeiyuYang** [comment]
好的，如果方便请提供一个正方形的logo以供我站显示。
建议尺寸为 16x16 的png

**Comment by zhoujianwei** [comment]
![ico](https://user-images.githubusercontent.com/4134294/38192403-4fb3308a-369f-11e8-99e5-303d05a00400.png)
麻烦用这个图标，谢谢

**Comment by zhoujianwei** [comment]
@PeiyuYang 已经上传素材，劳烦贵站更新下

**Comment by PeiyuYang** [comment]
已经更新

**Comment by zhoujianwei** [comment]
@PeiyuYang 想问下，btc.com的实时算力转换成实时的而不是按照块估算的需要提供什么接口么？

**Comment by PeiyuYang** [comment]
@zhoujianwei  需要给我们一个贵站的算力接口，之后我们会定时抓取。
如果不方便公开可以发送到 webmaster@btc.com, 我们抓取一段时间后会自动转化成实时算力。

**Comment by zhoujianwei** [comment]
@PeiyuYang   多谢，建议取shares_15m为我们的实时算力
https://www.dpool.top/pool-summary

{"shares":{"shares_1m":"1227.33","shares_5m":"1252.52","shares_15m":"1254.30","shares_1h":"1260.78","shares_unit":"T"},"reject":{"1m":0,"5m":0,"15m":0.0015,"1h":0.0011},"workers_active":82181,"total_blocks":1032,"total_rewards":"1382050118222.00000000","hash_rate":"1254.30"}

**Comment by spica-star** [comment]
@zhoujianwei  已显示为实时算力，其他字段需要等收集足够数据后会自动显示

**Comment by zhoujianwei** [comment]
@spica-star   我们稍后在接口中加入24h  3d幸运值数据。这个数据你们是显示实时的还是utc 0的？

**Comment by PeiyuYang** [comment]
@zhoujianwei  目前幸运值我们是收集足够的算力数据去反推计算的，目前并不需要矿池提供这个数据。
如果你感觉数值偏差大的话可以找我处理

**Comment by zhoujianwei** [comment]
多谢

**Comment by neovivun** [comment]
make neovivum to threatment and open new

**Comment by neovivun** [comment]
restore pool who stolen
