### ISSUE TITLE
Space after address 15xiShqUqerfjFdyfgBH1K7Gwp6cbYmsTW

### ISSUE THREAD

**Issue by mutatrum** [btccom/Blockchain-Known-Pools#85]
This confuses some block explorers. See f.e. https://mempool.space/tx/1d790e532de73425f5ceaaa83829756f5358c0f14f78e553fde12eea691b684a, which is not attributed to EclipseMC.
![image](https://user-images.githubusercontent.com/56344102/117963308-7cdb3c00-b320-11eb-8b6a-5a4c243dd1e8.png)

**Comment by dubuqingfeng** [comment]
https://github.com/btccom/Blockchain-Known-Pools/commit/abb1e827805d58580060791cf5bfa685cfe689f3
