### ISSUE TITLE
Ok here is my coinbase wallet address

### ISSUE THREAD

**Issue by Yuttana12wr** [btccom/Blockchain-Known-Pools#90]
Ok here is my coinbase wallet address

qqssdsycr56r9lf5ttajxtp3eshk52ugxqg5pcfxzu

_Originally posted by @Sparky1ers in https://github.com/btccom/Blockchain-Known-Pools/issues/89#issuecomment-899836986_

**Comment by Sparky1ers** [comment]
Are you trying to help me recover my BCH ?  I don't have BTC only BCH

**Comment by Sparky1ers** [comment]
You can send to my PayPal
***@***.***
